-- Banco de dados E10
CREATE DATABASE LIVRARIA_IPUENSE;
USE LIVRARIA_IPUENSE;
CREATE TABLE CIDADE (
    ID_CID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    ESTADO INT NOT NULL,
);

CREATE TABLE BAIRRO (
    ID_BAIRRO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_BAIRRO VARCHAR(100) NOT NULL
);

CREATE TABLE RUA (
    ID_RUA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_RUA VARCHAR(100) NOT NULL,
    BAIRRO INT NOT NULL,

    CONSTRAINT FK_RUA_BAIRRO
    FOREIGN KEY (BAIRRO)
    REFERENCES BAIRRO(ID_BAIRRO)
);

CREATE TABLE LOCALIZACAO (
    LOCAL_ID INT AUTO_INCREMENT PRIMARY KEY,
    CIDADE INT NOT NULL,
    BAIRRO INT NOT NULL,
    RUA INT NOT NULL,
    N_CASA INT NOT NULL,

    CONSTRAINT FK_CIDADE
    FOREIGN KEY (CIDADE)
    REFERENCES CIDADE(ID_CID),

    CONSTRAINT FK_BAIRRO
    FOREIGN KEY (BAIRRO)
    REFERENCES BAIRRO(ID_BAIRRO),

    CONSTRAINT FK_RUA
    FOREIGN KEY (RUA)
    REFERENCES RUA(ID_RUA)
);

CREATE TABLE CLIENTES (
    CPF_CLI BIGINT PRIMARY KEY,
    NOME_CLI VARCHAR(100) NOT NULL,
    EMAIL_CLI VARCHAR(100)NULL,
    TEL_CLI INT NULL,
    LOCALIZACAO_CLI INT NULL,

    CONSTRAINT FK_LOCALIZACAO_CLI
    FOREIGN KEY (LOCALIZACAO_CLI)
    REFERENCES LOCALIZACAO(LOCAL_ID)
);

CREATE TABLE SETOR (
    ID_SET INT AUTO_INCREMENT PRIMARY KEY,
    NOME_SET VARCHAR(30) UNIQUE
);

CREATE TABLE TURNO (
    ID_TURNO INT AUTO_INCREMENT PRIMARY KEY,
    INICIO TIME NOT NULL,
    FINAL TIME NOT NULL
);

CREATE TABLE CARGA_HORARIA (
    ID_CARGA INT AUTO_INCREMENT PRIMARY KEY,
    TURNO1 INT NULL,
    TURNO2 INT NULL,
    TURNO3 INT NULL,

    CONSTRAINT FK_TURNO1
    FOREIGN KEY (TURNO1)
    REFERENCES TURNO(ID_TURNO),

    CONSTRAINT FK_TURNO2
    FOREIGN KEY (TURNO2)
    REFERENCES TURNO(ID_TURNO),

    CONSTRAINT FK_TURNO3
    FOREIGN KEY (TURNO3)
    REFERENCES TURNO(ID_TURNO)
);

CREATE TABLE ESCALA (
    ID_ESCALA INT AUTO_INCREMENT PRIMARY KEY,
    SEG INT NOT NULL,
    TER INT NOT NULL,
    QUA INT NOT NULL,
    QUI INT NOT NULL,
    SEX INT NOT NULL,
    SAB INT NOT NULL,

    CONSTRAINT FK_SEG
    FOREIGN KEY (SEG)
    REFERENCES CARGA_HORARIA(ID_CARGA),

    CONSTRAINT FK_TER
    FOREIGN KEY (TER)
    REFERENCES CARGA_HORARIA(ID_CARGA),

    CONSTRAINT FK_QUA
    FOREIGN KEY (QUA)
    REFERENCES CARGA_HORARIA(ID_CARGA),

    CONSTRAINT FK_QUI
    FOREIGN KEY (QUI)
    REFERENCES CARGA_HORARIA(ID_CARGA),

    CONSTRAINT FK_SEX
    FOREIGN KEY (SEX)
    REFERENCES CARGA_HORARIA(ID_CARGA),

    CONSTRAINT FK_SAB
    FOREIGN KEY (SAB)
    REFERENCES CARGA_HORARIA(ID_CARGA)
);

CREATE TABLE FUNCIONARIO (
    CPF_FUN BIGINT PRIMARY KEY,
    NOME_FUN VARCHAR(100) NOT NULL,
    SALARIO FLOAT NOT NULL CHECK (SALARIO > 0),
    SETOR INT NOT NULL,
    ESCALA_FUN INT NOT NULL,
    EMAIL_FUN VARCHAR(100) NULL,
    TEL_FUN INT NULL,
    LOCALIZACAO_FUN INT NOT NULL,

    CONSTRAINT FK_SETOR
    FOREIGN KEY (SETOR)
    REFERENCES SETOR(ID_SET),

    CONSTRAINT FK_ESCALA
    FOREIGN KEY (ESCALA_FUN)
    REFERENCES ESCALA(ID_ESCALA),

    CONSTRAINT FK_LOCALIZACAO_FUN
    FOREIGN KEY (LOCALIZACAO_FUN)
    REFERENCES LOCALIZACAO(LOCAL_ID)
);

CREATE TABLE CATEGORIAS (
    ID_CATEG INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CATEG VARCHAR(40) UNIQUE
);

CREATE TABLE PRODUTO (
    ID_PRO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PRO VARCHAR(150) UNIQUE,
    PRECO FLOAT NOT NULL CHECK (PRECO >= 0),
    ESTOQUE INT DEFAULT 0 CHECK (ESTOQUE >= 0),
    CATEGORIA INT NOT NULL,

    CONSTRAINT FK_PRODUTO_CATEGORIA
    FOREIGN KEY (CATEGORIA)
    REFERENCES CATEGORIAS(ID_CATEG)
);

CREATE TABLE LIVRO (
    ID_LIVRO INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(150) NOT NULL,
    VOLUME INT NOT NULL,
    CATEGORIA INT NOT NULL,
    PRECO FLOAT NOT NULL CHECK (PRECO >= 0),
    AUTOR VARCHAR(100) NOT NULL,
    ESTOQUE INT DEFAULT 0 CHECK (ESTOQUE >= 0),

    CONSTRAINT FK_LIVRO_CATEGORIA
    FOREIGN KEY (CATEGORIA)
    REFERENCES CATEGORIAS(ID_CATEG)
);

CREATE TABLE FORNECEDORA (
    ID_FOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME_FOR VARCHAR(50) NOT NULL,
    EMAIL_FOR VARCHAR(60) NULL,
    TEL_FOR INT NULL,
    SITE_FOR VARCHAR(100) NULL
);

CREATE TABLE ENCOMENDA_PRODUTO (
    ID_ENC_PRO INT AUTO_INCREMENT PRIMARY KEY,
    FORNECEDORA INT NOT NULL,
    PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRECO FLOAT NOT NULL,
    DIA DATE NOT NULL,
    HORA TIME NOT NULL,

    CONSTRAINT FK_ENC_PRO_FOR
    FOREIGN KEY (FORNECEDORA)
    REFERENCES FORNECEDORA(ID_FOR),

    CONSTRAINT FK_ENC_PRODUTO
    FOREIGN KEY (PRODUTO)
    REFERENCES PRODUTO(ID_PRO)
);

CREATE TABLE ENCOMENDA_LIVRO (
    ID_ENC_LIVRO INT AUTO_INCREMENT PRIMARY KEY,
    FORNECEDORA INT NOT NULL,
    LIVRO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRECO FLOAT NOT NULL,
    DIA DATE NOT NULL,
    HORA TIME NOT NULL,

    CONSTRAINT FK_ENC_LIVRO_FOR
    FOREIGN KEY (FORNECEDORA)
    REFERENCES FORNECEDORA(ID_FOR),

    CONSTRAINT FK_ENC_LIVRO
    FOREIGN KEY (LIVRO)
    REFERENCES LIVRO(ID_LIVRO)
);

CREATE TABLE FORMA_PAGAMENTO (
    ID_PAG INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PAG VARCHAR(30) UNIQUE
);

CREATE TABLE COMPRA (
    ID_COMPRA INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE BIGINT NOT NULL,
    FUNCIONARIO BIGINT NOT NULL,
    PAGAMENTO INT NOT NULL,
    DIA DATE NOT NULL,
    HORA TIME NOT NULL,

    CONSTRAINT FK_COMPRA_CLIENTE
    FOREIGN KEY (CLIENTE)
    REFERENCES CLIENTES(CPF_CLI),

    CONSTRAINT FK_COMPRA_FUNCIONARIO
    FOREIGN KEY (FUNCIONARIO)
    REFERENCES FUNCIONARIO(CPF_FUN),

    CONSTRAINT FK_COMPRA_PAGAMENTO
    FOREIGN KEY (PAGAMENTO)
    REFERENCES FORMA_PAGAMENTO(ID_PAG)
);

CREATE TABLE HISTORICO_VENDA_PRODUTO (
    ID_HIST_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    COMPRA INT NOT NULL,
    PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL CHECK (QUANTIDADE > 0),
    PRECO_UNITARIO FLOAT NOT NULL CHECK (PRECO_UNITARIO >= 0),

    CONSTRAINT FK_HIST_COMPRA_PRODUTO
    FOREIGN KEY (COMPRA)
    REFERENCES COMPRA(ID_COMPRA),

    CONSTRAINT FK_HIST_PRODUTO
    FOREIGN KEY (PRODUTO)
    REFERENCES PRODUTO(ID_PRO)
);

CREATE TABLE HISTORICO_VENDA_LIVRO (
    ID_HIST_LIVRO INT AUTO_INCREMENT PRIMARY KEY,
    COMPRA INT NOT NULL,
    LIVRO INT NOT NULL,
    QUANTIDADE INT NOT NULL CHECK (QUANTIDADE > 0),
    PRECO_UNITARIO FLOAT NOT NULL CHECK (PRECO_UNITARIO >= 0),

    CONSTRAINT FK_HIST_COMPRA_LIVRO
    FOREIGN KEY (COMPRA)
    REFERENCES COMPRA(ID_COMPRA),

    CONSTRAINT FK_HIST_LIVRO
    FOREIGN KEY (LIVRO)
    REFERENCES LIVRO(ID_LIVRO)
);
